export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const FETCH_COMMENTS_REQUEST = "FETCH_COMMENTS_REQUEST";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const FETCH_COMMENTS_FALIURE = "FETCH_COMMENTS_FALIURE";
